### ISSUE TITLE
Teleporting zombies to world origin if game decides there is not enough space happens way too often

### ISSUE THREAD

**Issue by Fichtendummkopf** [zm-reborn/zmr-game#302] opened 2020-01-12 16:57 UTC
This is about the aggressive behavior of teleporting zombies to world origin  as soon as they would be likely to become a bit stuck after spawning.

I first noticed it with zombiespawns on one of my maps, using the new trigger_spawnvolume.
The spawnvolume brush should have been big enough for the banshees spawning in the spawn, but they would still spawn/teleport at/to world origin (I was able to fix it by using the old spawnnode setup instead.)

But it does not only happen when a zombie spawns:
Currently, this also occurs when you teleport a zombie ( e.g. with point_teleport, which I tried as workaround to prevent the npc_maker's zombie from spawning at world origin):
I used point_teleport to teleport the zombie that spawns somewhere else, but it immediately gets teleported back to origin, as the game seems to decide there is no space.
I can re-teleport with the point_teleport a few times until it decides there is enough space and the zombie finally stays. (granted, in this situation there are some physboxes in the way, but since they are mobile I do not think design-whise they should block zombie spawning)

Could that teleport-to-origin behavior be disabled for everything but when a zombie initally spawns if it isn't gonna be disabled completely? 

To me, it would even be preferable to have a few zombies stuck where you can actually see them, rather than having them eat up resources somewhere at the world origin.

**Comment by L1pE** [comment] 2020-01-13 15:12
This also affects the ninja banshee in zm_kink, which teleports inside the police station stairs. It's possibly caused by its bomb, which spawns with it, invisible, and flips out for a bit before moving to the banshee's position. The bomb might also not be acting as it should on spawn, as there's another issue with a prop in the map, namely, the weed bag once set on fire.

**Comment by DevilMudger** [comment] 2020-01-13 22:09
I can think of a few other traps spawn zombies and they get teleported to the origin by this. One in projectnightmare and one in sexshop. I'm sure there are others though. Anywhere where the zombie spawns in a very confined space seems to trigger it.

To me, letting the zombies get stuck is preferable.

**Closed** 2020-02-03 15:08 UTC
Labels: bug, enhancement
