### ISSUE TITLE
[ Bug / Steam-ver ] Control binds resetting on round restart

### ISSUE THREAD

**Issue by DoofusCockslap** [zm-reborn/zmr-game#228] opened 2019-02-12 13:13 UTC
The controls are resetting every round restart. As was stated, related to ZM and Survivor control schemes conflicting with one another due to the different commands being bound to the same shared key.
For example ZM's hidden summon hotkey and survivor's reloading being tied to "R" key.

**Comment by TotallyMehis** [comment] 2019-02-28 18:57
Duplicate of #216?

**Closed** 2019-02-28 19:14 UTC
Labels: bug, duplicate, unreleased
