### ISSUE TITLE
Korean Font Support

### ISSUE THREAD

**Issue by aisaka-taiga** [zm-reborn/zmr-game#266] opened 2019-07-27 07:59 UTC
![이미지 2](https://user-images.githubusercontent.com/15984396/61991739-d1e88800-b08f-11e9-90e9-4677761ca20e.png)
The main menu is broken because there is no Korean font I think.
Before Reborn was fine.

**Comment by TotallyMehis** [comment] 2019-07-27 08:46
Addressed in e64c0b84351daa16da70a0bc89039a7f12b2c40c
Duplicate of #263

**Closed by TotallyMehis** 2019-07-27 08:46 UTC
Labels: duplicate, enhancement
